### ISSUE TITLE
After a point it stops showing comments.

### ISSUE THREAD

**Issue by punit1108** [Bajrangbana/Interactive_Comment_Section#1]
<img width="677" alt="Screenshot 2024-07-17 at 10 54 43 AM" src="https://github.com/user-attachments/assets/2b99cc1a-8f41-4e99-bc1b-74f9c341b491">

**Comment by Bajrangbana** [comment]
fixed above issue now you can add reply with no limits 


<img width="409" alt="image" src="https://github.com/user-attachments/assets/e0b5d4e3-b1b9-46c8-a6c6-9ff142a1af22">
